version: '3'
services:
  app:
    build: ./app/
    command: ["sh", "-c", "sleep 15 && pnpm dev:docker"]
    restart: always
    depends_on:
      - server
    ports:
      - '51818:51818'

  server:
    build: ./server/
    restart: always
    depends_on:
      - database
    ports:
      - '51717:51717'

  database:
    build: ./database/
    restart: always
    ports:
      - '52020:3306'

